// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Movable, MovableTableId } from "./tables/Movable.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { ActivePlayer, ActivePlayerData, ActivePlayerTableId } from "./tables/ActivePlayer.sol";
