// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPlayerSystem {
  function registerPlayer1() external returns (address);

  function registerPlayer2() external returns (address);
}
