// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPositionSystem {
  function moveUp() external returns (uint32);

  function moveDown() external returns (uint32);

  function moveLeft() external returns (uint32);

  function moveRight() external returns (uint32);
}
